// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gorm.io/gorm"
	"learn-sqs/app/service/lambda/handler"
	"learn-sqs/app/service/lambda/usecase"
)

// Injectors from wire.go:

func Wire(db *gorm.DB) handler.Handler {
	messageUsecase := usecase.NewMessageUsecase(db)
	handlerHandler := handler.NewHandler(messageUsecase)
	return handlerHandler
}
