// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gorm.io/gorm"
	"learn-sqs/app/service/api/presentation/controller"
)

// Injectors from wire.go:

func Wire(db *gorm.DB) controller.Controllers {
	healthController := controller.NewHealthController(db)
	controllers := controller.NewControllers(healthController)
	return controllers
}
