// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gorm.io/gorm"
	"learn-sqs/app/pkg/sqs"
	"learn-sqs/app/service/api/presentation/controller"
)

// Injectors from wire.go:

func Wire(db *gorm.DB, sqs *sqsclient.Sqs) controller.Controllers {
	healthController := controller.NewHealthController(db)
	messageController := controller.NewMessageController(db, sqs)
	controllers := controller.NewControllers(healthController, messageController)
	return controllers
}
